from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import Paragraph
from reportlab.platypus import Spacer
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet


def create_report(outputPath):

    document=SimpleDocTemplate(
        outputPath,
        pagesize=letter
    )
    styles=getSampleStyleSheet()
    elements=[]
    title=Paragraph(
        "AI Business Intelligence Report",
        styles["Title"]
    )

    elements.append(title)

    elements.append(Spacer(1,20))

    heading=Paragraph(
        "Executive Summary",
        styles["Heading1"]
    )

    elements.append(heading)
    elements.append(Spacer(1,20))

    summary=Paragraph(
        "This is a test business report generated by the AI Business Intelligence Assistant.",
        styles["BodyText"]
    )

    elements.append(summary)

    document.build(elements)


if __name__ == "__main__":
    create_report("business_report.pdf")

